package com.example.calendarapp;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "events")
public class EventModel {

    @PrimaryKey(autoGenerate = true)
    public int id;
    
    public String date;
    public String time;
    public String title;

    public EventModel(int id, String date, String time, String title) {
        this.id = id;
        this.date = date;
        this.time = time;
        this.title = title;
    }

    // Room needs a constructor or getters/setters. 
    // Since id is autogenerated, we often provide a constructor without ID for inserts.
    @Ignore
    public EventModel(String date, String time, String title) {
        this.date = date;
        this.time = time;
        this.title = title;
    }
}
